kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-edit
  namespace: apidev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "d433c65b-7751-4186-8b86-0d368347c195"
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-view-webdev
  namespace: webdev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "d433c65b-7751-4186-8b86-0d368347c195"
  apiGroup: rbac.authorization.k8s.io