
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-access
  namespace: apidev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apidev-role
subjects:
- kind: User
  namespace: apidev
  name: b1a3efab-faeb-479b-8797-9b182f0522e7
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-view
  namespace: apidev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  namespace: apidev
  name: b1a3efab-faeb-479b-8797-9b182f0522e7