kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apidev-edit
  namespace: apidev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: "b1a3efab-faeb-479b-8797-9b182f0522e7"
  apiGroup: rbac.authorization.k8s.io