kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-role
  namespace: webdev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]