kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-edit
  namespace: webdev
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: "930021c0-2c5c-47fc-bcfd-ff02eae95552"
  apiGroup: rbac.authorization.k8s.io